version: 1.7.6.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: v141

platform:
    - Any CPU

configuration:
    - Release

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Any CPU" set archi=x86
    - if "%platform%"=="Any CPU" set platform_input=Any CPU

    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\source\Tests\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\Source\packages


init:
    - git config --global core.autocrlf true


build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\source
    - if "%PlatformToolset%"=="v141" msbuild csscript.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    # - cd "%APPVEYOR_BUILD_FOLDER%"\source\build

artifacts:
  - path: CSScript_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v141
        configuration: Release
