# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: oleg-shilo.cs-script
PackageVersion: 4.8.7
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cs-script.win.v4.8.7.0\cscs.exe
  PortableCommandAlias: css
Installers:
- InstallerUrl: https://github.com/oleg-shilo/cs-script/releases/download/v4.8.7.0/cs-script.win.v4.8.7.0.zip
  Architecture: neutral
  InstallerSha256: D481B721DD31628AE7D21DB445D43260DB4B6F3ECC07BC8AE4E0B8727D1FEA24
ManifestType: installer
ManifestVersion: 1.5.0
